### PR TITLE
Fix extended # 24

### PR DESCRIPTION
**Pull request by vegarringdal**
@kyr0 

Ive made some modifications, see for issue #24 
PS! Ive allready bumped the package.json to beta 6.

Can you have a look and see if this works with you framework.

### CODE REVIEW

**Comment by vegarringdal** [comment]
@kyr0 

Added fix for what you told me on slack here the other day.
Not it check that observedAttributes is array before trying to use it. 👍

**Comment by vegarringdal** [comment]
@LarsDenBakker

Hi, dunno if you still use this polyfill. But if you also chance to test the current version with you work than that would be great. Just want to be sure I havent broken anything. 
I need this fix for my weird little [simple-html](https://github.com/simple-html/simple-html) helper lib

**Comment by LarsDenBakker** [comment]
Yes im still using this, though finishing the work on systemjs first. Wont be able to test until next week, so id say go ahead and merge it.

**Comment by vegarringdal** [comment]
@LarsDenBakker 

OK, still want @kyr0 to get a chance to have a look/test before I merge it.
Just incase he sees something I didnt think about/better solution.
There is no rush since Im the only one having issues with this atm 😄

**Comment by vegarringdal** [comment]
@LarsDenBakker

Did you get a chance to test ?

**Comment by vegarringdal** [comment]
Hi @kyr0 
Are you still busy ?
If so I will most likely merge and update

**Comment by kyr0** [comment]
Okay, this looks good to me

**Pull request merged**
